version: '3.9'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql

  python:
    container_name: agency
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/srv/www/agency
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db






