# Generated by Django 4.1.10 on 2023-07-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name']},
        ),
    ]
